# Generated by Django 3.2.12 on 2023-08-10 10:08

import django.core.validators
from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image_encode', models.ImageField(blank=True, null=True, upload_to=media.models.upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='PDFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('pdf_encode', models.FileField(blank=True, null=True, upload_to=media.models.upload_pdf, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
