# Generated by Django 3.2.12 on 2023-08-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_encode',
            new_name='file_encode',
        ),
        migrations.RenameField(
            model_name='pdfs',
            old_name='pdf_encode',
            new_name='file_encode',
        ),
    ]
